name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: npx pnpm i

      - name: Cache fonts
        uses: actions/cache@v3
        id: cache-fonts
        with:
          path: fonts/
          key: font-lxgw-wenkai

      - name: Download fonts
        if: steps.cache-fonts.outputs.cache-hit != 'true'
        uses: robinraju/release-downloader@v1.8
        with:
          repository: lxgw/LxgwWenKai
          tag: v1.250
          fileName: "*.ttf"
          tarBall: false
          zipBall: false
          out-file-path: fonts/

      - name: Install fonts
        run: |
          sudo mkdir -p /usr/share/fonts/TTF/
          sudo cp fonts/*.ttf /usr/share/fonts/TTF/
          sudo fc-cache -fv
          fc-list | grep LXGW
        shell: bash

      - name: Update sponsors
        run: npm -C packages/sponsorkit run build && npm run sponsors
        env:
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}

      - name: Upload sponsors artifact
        uses: actions/upload-artifact@v3
        with:
          name: sponsor-artifact
          path: sponsors
  
  update-snk:
    runs-on: ubuntu-latest

    steps:
      - name: Update snk
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snk/contribution-snake.svg
            snk/contribution-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snk artifact
        uses: actions/upload-artifact@v3
        with:
          name: snk-artifact
          path: snk

  commit-changes:
    runs-on: ubuntu-latest
    needs: [ update-snk, update-sponsors ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download sponsors artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: sponsor-artifact
          path: sponsors

      - name: Download snk artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: snk-artifact
          path: snk

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update static files"
          add: |
            sponsors/*
            snk/*
          author_name: 401U
          author_email: hi@4o1.to
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
